### ISSUE TITLE
voice for class needed

### ISSUE THREAD

**Issue by lujun9972** [stardiviner/emacs-rainbow-fart#10]

**Comment by stardiviner** [comment]
最近发现有一些新的rainbow-fart的扩展包是扩展语音的。我有时间去看看，有没有适合class的语音包。

**Comment by lujun9972** [comment]
https://github.com/Nanguage/Rainbow-Fart-MBG

马保国语音包，搞起啊~

**Comment by stardiviner** [comment]
很久没来看这个插件了，之前确实一直想支持第三方语音报。现在rainbow-fart的语音报应该不少。最好是能直接兼容vscode那样的配置方式。不知道Emacs下有没有什么办法实现？

**Comment by stardiviner** [comment]
我查看了这个仓库的access权限，很早之前就给你发过collaborator邀请。我再给你发一次。我最近有点忙，不一定能抽出时间来改进这个包，所以你要是有想法的话，可以改进他。

**Comment by stardiviner** [comment]
https://github.com/stardiviner/emacs-rainbow-fart/invitations

**Comment by lujun9972** [comment]
好像邀请过期了:joy:

**Comment by stardiviner** [comment]
ok, 重新邀请了

**Comment by lujun9972** [comment]
马宝国现在开始限流量了，我想想还是不加入了吧。

**Comment by stardiviner** [comment]
恩恩，我对这个互联网热词完全不知道，也是你说了之后才去看了下。class的voice我另外想想。

**Comment by stardiviner** [comment]
新添加了第三方语音包的支持。所以导入语音报变得容易了。我找了几个语音包，都没有添加类的语音。虽然没有实际解决这个问题。等将来第三方语音包解决吧。先关闭了。

https://github.com/stardiviner/emacs-rainbow-fart/commit/913cdff84e8b0f47d1745f5eba360e4ad76b99e9
