### ISSUE TITLE
Error running timer "rainbow-fart-play"

### ISSUE THREAD

**Issue by nicehiro** [stardiviner/emacs-rainbow-fart#3]
如果使用 use-package 安装的话，在 elpa 目录下的 rainbow-fart 目录中找不到 voice 文件，需要手动复制。

**Comment by stardiviner** [comment]
Which method of use-package do you use to install this package?
Currently this package is not on MELPA yet, so not `:ensure`.
I guess something like `:quelpa`. I remember it supports all files. Maybe you setted `:files` etc to limited only elisp files. Should not set this option.
So can you paste your config here?

**Comment by nicehiro** [comment]
```
(use-package rainbow-fart
	:quelpa (rainbow-fart :repo "stardiviner/emacs-rainbow-fart" :fetcher github)
	:hook
	((prog-mode . rainbow-fart-mode))
	:custom
	(rainbow-fart-keyword-interval (* 60 1) "voice output interval.")
	)
```
At first I use `:ensure` option, it failed to copy `voice` directory. Then I delete this option, use above config still not work.

**Comment by stardiviner** [comment]
I guess you use it wrong.
Anyway, my config works fine.
```
(use-package rainbow-fart
  :quelpa (rainbow-fart :fetcher "github" :repo "stardiviner/emacs-rainbow-fart")
  :hook (prog-mode . rainbow-fart-mode))
```

**Comment by nicehiro** [comment]
Sorry it still not work. 

I close it because it looks like a quelpa problem. Thanks.
