### ISSUE TITLE
Font face judge not works fine in every time

### ISSUE THREAD

**Issue by locez** [stardiviner/emacs-rainbow-fart#6]
set this in packages.el,  it use  Straight to  fetch files , all function loaded but no sound.
```
(package! rainbow-fart :recipe
  (:host github
   :repo "stardiviner/emacs-rainbow-fart"
   :branch "master"
   :files ("*.el" "voices" ".dir-locals.el")))
```

before I try this repo,I have use `/DogLooksGood/rainbow-fart.el` which work good, but keywords too less.

emacs-27

====

timer event works normal

```
time_evening_01.mp3 ...
```

**Comment by stardiviner** [comment]
Sorry, I don't know straight. But I think your problem is similar with #3 .
Can you try to installed without `:files` ?

**Comment by locez** [comment]
without `:files` also not work. When I step to step debug in this function. sometimes it could paly the `for` keyword's voice.But mostly not work normal.

**Comment by locez** [comment]
#4 make this bug, I don't know why sometimes can't get the font face (maybe it's too quickly to execute. when step to step by hand, it slow enough. I remove condition judge for font face every thing looks good. please fix this in upstream

**Comment by stardiviner** [comment]
Thanks for detailed debug info. Can you show the result of `(get-text-property (- (point) 1) 'face)` in your Emacs? Need to know the reason. Thanks

**Comment by stardiviner** [comment]
I tested on my machine, confirmed this problem. I reverted #4 PR in master branch at first. Maybe need to dig deeper. For now, don't know why.

**Comment by lujun9972** [comment]
你们两个中国人用英文交流不累么…
你们给个环境我复现一下？很奇怪我试是可以的…

**Comment by lujun9972** [comment]
(get-text-property (- (point) 1) 'face)的结果是什么呢？

**Comment by stardiviner** [comment]
有可能是 font-lock delay 延迟的缘故，有的时候没有播放。edebug的时候也是，有的时候能够获取到值正确，有的时候是 `nil`.

**Comment by lujun9972** [comment]
font-lock-defaults
这个变量值是什么呢？

**Comment by lujun9972** [comment]
How about only play  when `(get-text-property (- (point) 1) 'face)` returns `nil` or `font-lock-keyword-face`?

**Comment by stardiviner** [comment]
其实主要是要规避注释，可以not `font-lock-comment-face`.

**Comment by stardiviner** [comment]
`font-lock-defaults` 的值是
```
((lisp-el-font-lock-keywords lisp-el-font-lock-keywords-1 lisp-el-font-lock-keywords-2)
 nil nil nil nil
 (font-lock-mark-block-function . mark-defun)
 (font-lock-extra-managed-props help-echo)
 (font-lock-syntactic-face-function . lisp-font-lock-syntactic-face-function))
```

**Comment by locez** [comment]
这是一个 `buffer-local` 变量, 不同的 `buffer` 会不同
比如在 一个 `.go` 文件是

```
(go--build-font-lock-keywords)
```
在一个 `.sh` 文件是

```
((sh-font-lock-keywords sh-font-lock-keywords-1 sh-font-lock-keywords-2)
 nil nil
 ((47 . "w")
  (126 . "w")
  (46 . "w")
  (45 . "w")
  (95 . "w"))
 nil
 (font-lock-syntactic-face-function . sh-font-lock-syntactic-face-function))
```

**Comment by lujun9972** [comment]
I give up. The merchanism of font-lock is too much complicated.....
use `not in` is a good idea!

**Comment by stardiviner** [comment]
Ok, I will try the `not` solution, I will test on my machine at first. Thanks for diving in.

**Comment by stardiviner** [comment]
我测试了一下一些特殊情况，还是你们之前说的加上 `(null face)` 这样的条件判断比较好。
我再等一会儿，没有异议的话，我就推送了。

**Comment by lujun9972** [comment]
哦，也好

**Comment by lujun9972** [comment]
你说的特殊情况指的是哪些情况呢？

**Comment by stardiviner** [comment]
Org Mode 里开启 `lsp-org` 以及 `magit` 的一些buffer里面 还有 Clojure REPL 里面使用了空格的情况。比如
```

user> (

       if )
```
这样的奇葩情况。主要是可能来自于粘贴的代码。

**Comment by stardiviner** [comment]
这些情况应该是 `font-lock` 没有正确高亮代码的规则匹配的情况。
