### ISSUE TITLE
A command to help recording fart audio needed

### ISSUE THREAD

**Issue by lujun9972** [stardiviner/emacs-rainbow-fart#8]
1. prompt for the keyword, using the current symbol as the default value.
2. execute recorder command to record the fart audio with the audio file named `keyword-XXX.mp3` locating under the `rainbow-fart-voice-directory/rainbow-fart-voice-model` directory.

**Comment by stardiviner** [comment]
Sounds good idea. This will improving voice resource.

I used to try to implement recorder in Emacs, but have not found good solution. Do you have any good idea? Especially under Linux.

I will try to implement this at first and keep a `defcustom` option around to leave to recorder command.

**Comment by stardiviner** [comment]
Ok, I already added a command to record voice file for keyword. I pushed in separate branch "support-record-voice".
There is another task need to do, because can't deciced multiple recorded voice files for single keyword. So I decied to improve current voices matching keyword mechanism.
Use `<keyword>_<random string>.mp3` rule to match all voice files. Still considering in mind.
WDYT?

**Comment by lujun9972** [comment]
what you mean · can't deciced multiple recorded voice files for single keyword·？

**Comment by stardiviner** [comment]
Aha, good idea, It sounds like a quick solution. But `rainbow-fart-voice-alist` is static. What if user recorded multiple voices for `if` keyword like 10 voices? That will exceed the values in `rainbow-fart-alist`.

**Comment by lujun9972** [comment]
There is a problem. `defun`,`defn`,`function` are all used to define a function. That's why they are using the same voice list. 
If we search voice files using the keyword as a prefix, that will be many duplication files.

**Comment by stardiviner** [comment]
The `rainbow-fart-voice-alist` data structure need to be re-designed. I used to try use structure like:
```
'(("defun" "defn" "function" ...) . ("function_01.mp3" "function_02.mp3" ...) ...)
```
But this style structure still have problem.
Do you have any good suggestion?
Because it need to match two side, the key part for matching keywords, and the value part for matching voice files.

**Comment by lujun9972** [comment]
We can do something like this:
`'(("defun" "defn" "function" ...) . function ...)`
and then if keyword is one of `("defun" "defn" "function" ...)`, we search all the `keyword-XXXXX.mp3` under the rainbow-fart-voice-directory/rainbow-fart-voice-model directory.

**Comment by stardiviner** [comment]
Then how to handle other matching. In `rainbow-fart-voice-alist` contains not just programming keywords. Also contains other timely etc

**Comment by lujun9972** [comment]
The same way:
`'(("hour") . TimeEachHour)`
means searching all the 
`rainbow-fart-voice-directory/rainbow-fart-voice-model/TimeEachHour-xxxx.mp3` files

**Comment by stardiviner** [comment]
Hmm, seems ok, we also can rename voice filenames later if necessary.
Is my branch "support-record-voice" code ok? If that's ok, I will merge it into master, then start to develop next change (mainly the `rainbow-fart-voice-alist` change)

**Comment by stardiviner** [comment]
I added you into collaborator. Maybe you want to improve the recording voice command better.

**Comment by lujun9972** [comment]
There are some mistakes, I'll fix it later

**Comment by stardiviner** [comment]
That's great. :smiley_cat:

**Comment by stardiviner** [comment]
The record command is added in PR #11
